/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siskrip;
    import java.sql.*;
    import javax.swing.*;

/**
 * @author ASUS
 */
public class BerandaMhs extends javax.swing.JFrame {
    private String nim_nidn;

    // Konstruktor baru dengan parameter ID mahasiswa
    public BerandaMhs() {
        if (Session.nim_nidn == null) {
            JOptionPane.showMessageDialog(this, "Akses ditolak! Silahkan login dahulu.");
            System.exit(0);
        }
        this.nim_nidn = Session.nim_nidn;  // Ambil dari variabel static Session
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        tampilkanDataMahasiswa();
        tampilkanStatusJudul();
        tampilkanStatusSkripsi();
    }

    private void tampilkanDataMahasiswa() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/siskrip", "root", "");
            String sql = "SELECT nama, nim_nidn FROM users WHERE nim_nidn = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nim_nidn);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String nama = rs.getString("nama");
                NamaMhs.setText("HALO, " + nama.toUpperCase());
                NimMhs.setText("NIM : " + nim_nidn);
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    
    private void tampilkanStatusJudul() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/siskrip", "root", "");
            String sql = "SELECT judul, status FROM judulskripsi WHERE mahasiswa_id = ? ORDER BY judul_id DESC LIMIT 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Session.user_id);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String judul = rs.getString("judul");
                String status = rs.getString("status");
                stsNamaJudul.setText(judul);
                stsJudul.setText(status);  // ← Label di GUI Anda
            } else {
                stsNamaJudul.setText("Belum Mengajukan");
                stsJudul.setText("Belum Mengajukan");
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat status judul: " + e.getMessage());
        }
    }
    
    private void tampilkanStatusSkripsi() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/siskrip", "root", "");
            String sql = "SELECT nama_file, status FROM dokumenskripsi WHERE mahasiswa_id = ? ORDER BY dokumen_id DESC LIMIT 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Session.user_id);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String file = rs.getString("nama_file");
                String status = rs.getString("status");
                stsNamaFile.setText(file);
                stsSkripsi.setText(status);  // label di GUI Anda
            } else {
                stsNamaFile.setText("Belum Upload");
                stsSkripsi.setText("Belum Upload");
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat status skripsi: " + e.getMessage());
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NamaMhs = new javax.swing.JLabel();
        NimMhs = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        stsNamaJudul = new javax.swing.JLabel();
        stsJudul = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        stsSkripsi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stsNamaFile = new javax.swing.JLabel();
        btnJudul = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        btnKomentar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Profil = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 143, 202));

        NamaMhs.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NamaMhs.setForeground(new java.awt.Color(255, 255, 255));
        NamaMhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaMhs.setText("HALO, NAMA MAHASISWA");

        NimMhs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NimMhs.setForeground(new java.awt.Color(255, 255, 255));
        NimMhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NimMhs.setText("NIM : NIM MAHASISWA");
        NimMhs.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(130, 177, 226));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status Judul :");

        stsNamaJudul.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        stsNamaJudul.setForeground(new java.awt.Color(255, 255, 255));
        stsNamaJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stsNamaJudul.setText("nama");
        stsNamaJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        stsJudul.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        stsJudul.setForeground(new java.awt.Color(255, 255, 255));
        stsJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stsJudul.setText("Disetujui/Tidak");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stsJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stsNamaJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stsNamaJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stsJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(130, 177, 226));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        stsSkripsi.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        stsSkripsi.setForeground(new java.awt.Color(255, 255, 255));
        stsSkripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stsSkripsi.setText("Disetujui/Revisi");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status Skripsi :");

        stsNamaFile.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        stsNamaFile.setForeground(new java.awt.Color(255, 255, 255));
        stsNamaFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stsNamaFile.setText("nama");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stsSkripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stsNamaFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stsNamaFile, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stsSkripsi))
        );

        btnJudul.setBackground(new java.awt.Color(130, 177, 226));
        btnJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnJudul.setForeground(new java.awt.Color(255, 255, 255));
        btnJudul.setText("Ajukan Judul");
        btnJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJudulActionPerformed(evt);
            }
        });

        btnUpload.setBackground(new java.awt.Color(130, 177, 226));
        btnUpload.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(255, 255, 255));
        btnUpload.setText("Upload Skripsi");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnKomentar.setBackground(new java.awt.Color(130, 177, 226));
        btnKomentar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnKomentar.setForeground(new java.awt.Color(255, 255, 255));
        btnKomentar.setText("Lihat Komentar");
        btnKomentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKomentar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NamaMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NimMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NamaMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NimMhs)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJudul)
                    .addComponent(btnUpload)
                    .addComponent(btnKomentar))
                .addGap(30, 30, 30))
        );

        jMenuBar2.setBackground(new java.awt.Color(54, 116, 181));

        jMenu1.setText("Menu");

        Profil.setText("Profil");
        Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilActionPerformed(evt);
            }
        });
        jMenu1.add(Profil);
        jMenu1.add(jSeparator1);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Logout);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJudulActionPerformed
        new Ajukan_Judul_Mhs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJudulActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        new Upload_Skripsi_Mhs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnKomentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomentarActionPerformed
        new Lihat_Komentar_Mhs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKomentarActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilActionPerformed
        new ProfilMhs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BerandaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BerandaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BerandaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BerandaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BerandaMhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logout;
    private javax.swing.JLabel NamaMhs;
    private javax.swing.JLabel NimMhs;
    private javax.swing.JMenuItem Profil;
    private javax.swing.JButton btnJudul;
    private javax.swing.JButton btnKomentar;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel stsJudul;
    private javax.swing.JLabel stsNamaFile;
    private javax.swing.JLabel stsNamaJudul;
    private javax.swing.JLabel stsSkripsi;
    // End of variables declaration//GEN-END:variables
}
