/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siskrip;

    import java.awt.*;
    import java.io.*;
    import java.sql.*;
    import javax.swing.*;
    import javax.swing.table.*;

/**
 *
 * @author ASUS
 */
public class DUSDsn extends javax.swing.JFrame {

    /**
     * Creates new form DUSDsn
     */
    public DUSDsn() {
        if (Session.nim_nidn == null) {
            JOptionPane.showMessageDialog(this, "Akses ditolak! Silahkan login dahulu.");
            System.exit(0);
        }
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        loadDataFile();
    }
    
    private void loadDataFile() {
    try {
        int judulId = Session.judul_id;

        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/siskrip", "root", "");
        String sql = "SELECT nama_file, url_file FROM dokumenskripsi WHERE judul_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, judulId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            txtNamaFile.setText(rs.getString("nama_file"));
            Session.filePath = rs.getString("url_file");  // simpan lokasi file ke session
        } else {
            txtNamaFile.setText("Belum ada file diupload.");
            Session.filePath = null;
        }

        rs.close();
        pst.close();
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data file: " + e.getMessage());
    }
}
    
    // Method untuk update status
    private void updateStatusSkripsi(String newStatus) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/siskrip", "root", "");
            String sql = "UPDATE dokumenskripsi SET status=? WHERE judul_id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, newStatus);
            pst.setInt(2, Session.judul_id);

            int updated = pst.executeUpdate();

            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "Status berhasil diubah menjadi: " + newStatus);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah status. Data tidak ditemukan.");
            }

            pst.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat update status: " + e.getMessage());
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamaFile = new javax.swing.JTextField();
        btnLihat = new javax.swing.JButton();
        btnSetujui = new javax.swing.JButton();
        btnRevisi = new javax.swing.JButton();
        btnKomentar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Beranda = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        Profil = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 143, 202));

        btnLihat.setText("Lihat");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });

        btnSetujui.setText("Setujui");
        btnSetujui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetujuiActionPerformed(evt);
            }
        });

        btnRevisi.setText("Revisi");
        btnRevisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisiActionPerformed(evt);
            }
        });

        btnKomentar.setText("Beri Komentar");
        btnKomentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSetujui)
                        .addGap(135, 135, 135)
                        .addComponent(btnRevisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(btnKomentar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNamaFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLihat)))
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLihat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetujui)
                    .addComponent(btnRevisi)
                    .addComponent(btnKomentar))
                .addGap(49, 49, 49))
        );

        jMenuBar2.setBackground(new java.awt.Color(54, 116, 181));

        jMenu1.setText("Menu");

        Beranda.setText("Beranda");
        Beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerandaActionPerformed(evt);
            }
        });
        jMenu1.add(Beranda);
        jMenu1.add(jSeparator9);

        Profil.setText("Profil");
        Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilActionPerformed(evt);
            }
        });
        jMenu1.add(Profil);
        jMenu1.add(jSeparator10);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Logout);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerandaActionPerformed
        new BerandaDsn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BerandaActionPerformed

    private void ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilActionPerformed
        new ProfilDsn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfilActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
    if (Session.filePath == null || Session.filePath.isEmpty()) {
        JOptionPane.showMessageDialog(this, "File belum tersedia untuk diunduh.");
        return;
    }

    try {
        File file = new File(Session.filePath);
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "File tidak ditemukan di path: " + Session.filePath);
            return;
        }

        // Buka file dengan aplikasi default
        Desktop.getDesktop().open(file);

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal membuka file: " + e.getMessage());
    }
    }//GEN-LAST:event_btnLihatActionPerformed

    private void btnSetujuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetujuiActionPerformed
        updateStatusSkripsi("Disetujui");
    }//GEN-LAST:event_btnSetujuiActionPerformed

    private void btnRevisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisiActionPerformed
        updateStatusSkripsi("Revisi");        
    }//GEN-LAST:event_btnRevisiActionPerformed

    private void btnKomentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomentarActionPerformed
        new KomentarDsn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKomentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DUSDsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DUSDsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DUSDsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DUSDsn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DUSDsn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Beranda;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem Profil;
    private javax.swing.JButton btnKomentar;
    private javax.swing.JButton btnLihat;
    private javax.swing.JButton btnRevisi;
    private javax.swing.JButton btnSetujui;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTextField txtNamaFile;
    // End of variables declaration//GEN-END:variables
}
