/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siskrip;

    import javax.swing.*;
    import java.awt.*;
    import java.sql.*;

/**
 *
 * @author ASUS
 */
public class Lihat_Komentar_Mhs extends javax.swing.JFrame {

    /**
     * Creates new form Lihat_Komentar_Mhs
     */
    public Lihat_Komentar_Mhs() {
    if (Session.nim_nidn == null) {
        JOptionPane.showMessageDialog(this, "Akses ditolak! Silahkan login dahulu.");
        System.exit(0);
    }
    initComponents();
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    panelKomentarTemplate.setVisible(false);

    // Pastikan JScrollPane tidak ada scroll horizontal
    scrollPaneKomentar.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

    loadKomentar();
}

    private void loadKomentar() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/siskrip", "root", "");
        String sql = "SELECT ks.judul, kb.komentar, kb.tanggal " +
                     "FROM komentarbimbingan kb " +
                     "JOIN dokumenskripsi ds ON kb.dokumen_id = ds.dokumen_id " +
                     "JOIN judulskripsi ks ON ds.judul_id = ks.judul_id " +
                     "WHERE kb.mahasiswa_id = ? " +
                     "ORDER BY kb.tanggal DESC";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, Session.user_id);

        ResultSet rs = pst.executeQuery();

        // Bersihkan panel terlebih dahulu
        panelKomentarContainer.removeAll();
        panelKomentarContainer.setLayout(new BoxLayout(panelKomentarContainer, BoxLayout.Y_AXIS));
        panelKomentarContainer.revalidate();
        panelKomentarContainer.repaint();

        while (rs.next()) {
            String judul = rs.getString("judul");
            String komentar = rs.getString("komentar");
            String tanggal = rs.getString("tanggal");

            // Buat panel baru meniru template
            JPanel panelBaru = new JPanel();
            panelBaru.setLayout(new BoxLayout(panelBaru, BoxLayout.Y_AXIS));
            panelBaru.setBorder(panelKomentarTemplate.getBorder());
            panelBaru.setBackground(panelKomentarTemplate.getBackground());

            // Atur batas lebar supaya tidak terlalu lebar
            panelBaru.setMaximumSize(new Dimension(600, Integer.MAX_VALUE));
            panelBaru.setAlignmentX(Component.LEFT_ALIGNMENT);

            // Judul
            JLabel lblJudul = new JLabel("Judul Skripsi: " + judul);
            lblJudul.setFont(lblJudulSkripsiTemplate.getFont());
            lblJudul.setAlignmentX(Component.LEFT_ALIGNMENT);

            // Komentar
            JTextArea txtKomentar = new JTextArea(komentar);
            txtKomentar.setLineWrap(true);
            txtKomentar.setWrapStyleWord(true);
            txtKomentar.setEditable(false);
            txtKomentar.setFont(txtKomentarTemplate.getFont());
            txtKomentar.setBackground(txtKomentarTemplate.getBackground());
            txtKomentar.setBorder(txtKomentarTemplate.getBorder());
            txtKomentar.setMaximumSize(new Dimension(580, 100)); // Lebar dibatasi
            txtKomentar.setAlignmentX(Component.LEFT_ALIGNMENT);

            // Tanggal
            JLabel lblTanggal = new JLabel("Tanggal: " + tanggal);
            lblTanggal.setFont(lblTanggalTemplate.getFont());
            lblTanggal.setForeground(lblTanggalTemplate.getForeground());
            lblTanggal.setAlignmentX(Component.LEFT_ALIGNMENT);

            // Tambahkan ke panel
            panelBaru.add(lblJudul);
            panelBaru.add(Box.createVerticalStrut(5));
            panelBaru.add(txtKomentar);
            panelBaru.add(Box.createVerticalStrut(5));
            panelBaru.add(lblTanggal);
            panelBaru.add(Box.createVerticalStrut(5));
            panelBaru.add(new JSeparator());

            // Tambah ke container
            panelKomentarContainer.add(Box.createVerticalStrut(10));
            panelKomentarContainer.add(panelBaru);
        }

        panelKomentarContainer.revalidate();
        panelKomentarContainer.repaint();

        rs.close();
        pst.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat komentar: " + e.getMessage());
    }
}




    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPaneKomentar = new javax.swing.JScrollPane();
        panelKomentarContainer = new javax.swing.JPanel();
        panelKomentarTemplate = new javax.swing.JPanel();
        lblJudulSkripsiTemplate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKomentarTemplate = new javax.swing.JTextArea();
        lblTanggalTemplate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Beranda = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        Profil = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 143, 202));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIHAT KOMENTAR");

        panelKomentarContainer.setLayout(new javax.swing.BoxLayout(panelKomentarContainer, javax.swing.BoxLayout.LINE_AXIS));

        lblJudulSkripsiTemplate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblJudulSkripsiTemplate.setText("judul skripsi");

        txtKomentarTemplate.setColumns(20);
        txtKomentarTemplate.setRows(5);
        txtKomentarTemplate.setText("isi komentar");
        jScrollPane1.setViewportView(txtKomentarTemplate);

        lblTanggalTemplate.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTanggalTemplate.setText("tanggal");

        javax.swing.GroupLayout panelKomentarTemplateLayout = new javax.swing.GroupLayout(panelKomentarTemplate);
        panelKomentarTemplate.setLayout(panelKomentarTemplateLayout);
        panelKomentarTemplateLayout.setHorizontalGroup(
            panelKomentarTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKomentarTemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKomentarTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudulSkripsiTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelKomentarTemplateLayout.createSequentialGroup()
                        .addGroup(panelKomentarTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTanggalTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelKomentarTemplateLayout.setVerticalGroup(
            panelKomentarTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKomentarTemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulSkripsiTemplate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggalTemplate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        panelKomentarContainer.add(panelKomentarTemplate);

        scrollPaneKomentar.setViewportView(panelKomentarContainer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scrollPaneKomentar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneKomentar))
        );

        jMenuBar2.setBackground(new java.awt.Color(54, 116, 181));

        jMenu1.setText("Menu");

        Beranda.setText("Beranda");
        Beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerandaActionPerformed(evt);
            }
        });
        jMenu1.add(Beranda);
        jMenu1.add(jSeparator9);

        Profil.setText("Profil");
        Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilActionPerformed(evt);
            }
        });
        jMenu1.add(Profil);
        jMenu1.add(jSeparator10);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Logout);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerandaActionPerformed
        new BerandaMhs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BerandaActionPerformed

    private void ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilActionPerformed
        new ProfilMhs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfilActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lihat_Komentar_Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lihat_Komentar_Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lihat_Komentar_Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lihat_Komentar_Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lihat_Komentar_Mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Beranda;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem Profil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblJudulSkripsiTemplate;
    private javax.swing.JLabel lblTanggalTemplate;
    private javax.swing.JPanel panelKomentarContainer;
    private javax.swing.JPanel panelKomentarTemplate;
    private javax.swing.JScrollPane scrollPaneKomentar;
    private javax.swing.JTextArea txtKomentarTemplate;
    // End of variables declaration//GEN-END:variables
}
